apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: local-secrets
  namespace: agent-factory
spec:
  type: secretstores.localenv
  version: v1
scopes:
- customer-success-fte
- sales-support-fte
- technical-support-fte
